# Generated by Django 5.1.3 on 2025-03-03 08:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment_data", models.CharField(max_length=120)),
                ("recommendation_text", models.TextField()),
                ("user_query", models.TextField()),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 3, 3, 14, 10, 10, 830712)
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
