# Generated by Django 5.1.3 on 2025-03-08 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentimentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment_data", models.CharField(max_length=120)),
                ("recommendation_text", models.TextField()),
                ("user_query", models.TextField()),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 3, 8, 8, 18, 54, 246195)
                    ),
                ),
                ("query_sentiment", models.CharField(default="", max_length=120)),
            ],
        ),
    ]
