# Generated by Django 5.1.3 on 2024-12-09 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 9, 9, 11, 42, 129412)
            ),
        ),
    ]
