# Generated by Django 5.1.3 on 2025-03-03 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 14, 15, 38, 587901)
            ),
        ),
    ]
