# Generated by Django 5.1.3 on 2025-03-08 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0003_alter_sentimentmodel_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 8, 10, 34, 36, 293113)
            ),
        ),
    ]
