# Generated by Django 5.1.3 on 2025-03-10 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0005_alter_sentimentmodel_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentimentmodel",
            name="sentiment_score",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="sentimentmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 10, 13, 55, 45, 782850)
            ),
        ),
    ]
