# Generated by Django 5.1.3 on 2025-03-03 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0006_alter_sentimentmodel_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentimentmodel",
            name="query_sentiment",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="sentimentmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 19, 46, 2, 82435)
            ),
        ),
    ]
