# Generated by Django 5.1.3 on 2025-02-06 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0007_alter_sentimentmodel_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 6, 7, 45, 23, 329160)
            ),
        ),
    ]
