# Generated by Django 5.1.3 on 2025-03-03 08:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_name",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=120, unique=True)),
                ("password", models.CharField(max_length=120)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 3, 3, 14, 10, 10, 829713)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_login_days", models.IntegerField()),
                ("login_streak", models.IntegerField()),
                ("positive_streak", models.IntegerField()),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
