# Generated by Django 5.1.3 on 2024-12-12 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 12, 14, 18, 2, 395960)
            ),
        ),
    ]
