# Generated by Django 5.1.3 on 2025-03-03 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_dashboardrecords_last_login_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 14, 39, 14, 509326)
            ),
        ),
    ]
