# Generated by Django 5.1.3 on 2025-02-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 5, 20, 12, 21, 46036)
            ),
        ),
    ]
