# Generated by Django 5.1.3 on 2025-03-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardrecords",
            name="last_login_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 15, 1, 14, 402065)
            ),
        ),
    ]
