# Generated by Django 5.1.3 on 2025-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_userprofile_profile_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardrecords",
            name="is_mood_saved",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dashboardrecords",
            name="mood_saved_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
