# Generated by Django 5.1.3 on 2025-03-03 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_dashboardrecords_last_login_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 19, 46, 2, 31564)
            ),
        ),
    ]
