# Generated by Django 5.1.3 on 2025-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_otprequest_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otprequest",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="otprequest",
            name="email",
            field=models.EmailField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
