# Generated by Django 5.1.3 on 2024-11-28 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 28, 9, 9, 15, 215743)
            ),
        ),
    ]
