# Generated by Django 5.1.3 on 2025-03-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="assistant_text",
            new_name="context",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user_query",
        ),
    ]
