# Generated by Django 5.1.3 on 2024-12-12 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_alter_chat_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 12, 14, 18, 2, 396992)
            ),
        ),
    ]
