# Generated by Django 5.1.3 on 2025-01-07 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_alter_chat_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 7, 13, 34, 47, 710145)
            ),
        ),
    ]
