# Generated by Django 5.1.3 on 2025-02-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_alter_chat_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 5, 20, 12, 21, 47077)
            ),
        ),
    ]
