# Generated by Django 5.1.3 on 2025-02-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0008_alter_chat_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
