# Generated by Django 5.1.3 on 2025-02-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0009_alter_chat_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user_id",
            field=models.CharField(max_length=255),
        ),
    ]
